import express from "express";
import authRouter from "../src/routes/auth.routes.js";
import cookieParser from "cookie-parser";
import morgan from "morgan";
const app = express();
app.use(express.json());
app.use(morgan("dev"));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use("/api/auth", authRouter);
export default app;
